/**
 * intelligence-cache-layer.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * Transparent caching middleware for the project intelligence aggregation service.
 *
 * Pattern: Cache-aside decorator — wraps the existing service without modifying it.
 * All cache reads/writes/invalidation are isolated here.
 *
 * Usage in route handlers:
 *   const summary = await cachedIntelligence.getEnvironmentalSummary(projectId);
 *
 * Cache invalidation:
 *   cachedIntelligence.invalidate(projectId)   — called after MRV cycle completion
 * ─────────────────────────────────────────────────────────────────────────────
 */

import {
  withCache,
  invalidateProjectCache,
  cacheKey,
  CACHE_TTL,
} from "../observability/intelligence-cache";
import { projectIntelligenceAggregationService } from "./project-intelligence-aggregation-service";
import { createLogger } from "../observability/structured-logger";

const logger = createLogger("IntelligenceCacheLayer");

export const cachedIntelligence = {
  /** Environmental summary: EHI, trajectory, quality score, cycle count */
  getEnvironmentalSummary: (projectId: string) =>
    withCache(
      cacheKey.summary(projectId),
      CACHE_TTL.SUMMARY,
      () => projectIntelligenceAggregationService.getEnvironmentalSummary(projectId)
    ),

  /** Chronological project timeline events */
  getTimeline: (projectId: string) =>
    withCache(
      cacheKey.timeline(projectId),
      CACHE_TTL.TIMELINE,
      () => projectIntelligenceAggregationService.getTimeline(projectId)
    ),

  /** Monitoring-only timeline events */
  getMonitoringTimeline: (projectId: string) =>
    withCache(
      `monitoring-timeline:${projectId}`,
      CACHE_TTL.TIMELINE,
      () => projectIntelligenceAggregationService.getMonitoringTimeline(projectId)
    ),

  /** Historical observations (optionally filtered by indicator) */
  getHistoricalObservations: (projectId: string, indicator?: string) =>
    withCache(
      `hist-obs:${projectId}:${indicator ?? "all"}`,
      CACHE_TTL.HISTORY,
      () => projectIntelligenceAggregationService.getHistoricalObservations(projectId, indicator)
    ),

  /** Indicator time-series for chart rendering */
  getTrendPreparation: (projectId: string, indicator: string) =>
    withCache(
      cacheKey.history(projectId, indicator),
      CACHE_TTL.HISTORY,
      () => projectIntelligenceAggregationService.getTrendPreparation(projectId, indicator)
    ),

  /** Environmental change detection (baseline vs snapshots) */
  getEnvironmentalChangeFoundation: (projectId: string) =>
    withCache(
      cacheKey.changes(projectId),
      CACHE_TTL.CHANGES,
      () => projectIntelligenceAggregationService.getEnvironmentalChangeFoundation(projectId)
    ),

  /** Baseline vs current comparison for a specific indicator */
  getBaselineVsCurrent: (projectId: string, indicator: string) =>
    withCache(
      `bvc:${projectId}:${indicator}`,
      CACHE_TTL.CHANGES,
      () => projectIntelligenceAggregationService.getBaselineVsCurrent(projectId, indicator)
    ),

  /** Satellite raster/thumbnail artifact metadata */
  getSatelliteArtifacts: (projectId: string) =>
    withCache(
      cacheKey.artifacts(projectId),
      CACHE_TTL.ARTIFACTS,
      () => projectIntelligenceAggregationService.getSatelliteArtifacts(projectId)
    ),

  /** Trend anomaly markers for timelines/charts */
  getTrendAnomalyMarkers: (projectId: string) =>
    withCache(
      `trend-anomalies:${projectId}`,
      CACHE_TTL.CHANGES,
      () => projectIntelligenceAggregationService.getTrendAnomalyMarkers(projectId)
    ),

  /** Composite restoration risk score */
  getRestorationRiskScore: (projectId: string) =>
    withCache(
      `risk-score:${projectId}`,
      CACHE_TTL.CHANGES,
      () => projectIntelligenceAggregationService.getRestorationRiskScore(projectId)
    ),

  /** Monitoring alerts generated by threshold/rule engine */
  getMonitoringAlerts: (projectId: string, persistToTimeline = false) =>
    withCache(
      `monitoring-alerts:${projectId}:${persistToTimeline ? "persist" : "ephemeral"}`,
      CACHE_TTL.CHANGES,
      () => projectIntelligenceAggregationService.getMonitoringAlerts(projectId, persistToTimeline)
    ),

  /** Automated environmental insight generation */
  getAutomatedInsights: (projectId: string) =>
    withCache(
      `auto-insights:${projectId}`,
      CACHE_TTL.SUMMARY,
      () => projectIntelligenceAggregationService.getAutomatedInsights(projectId)
    ),

  /** Long-term restoration trajectory classification */
  getLongTermTrajectory: (projectId: string) =>
    withCache(
      `trajectory:${projectId}`,
      CACHE_TTL.SUMMARY,
      () => projectIntelligenceAggregationService.getLongTermTrajectory(projectId)
    ),

  /** Seasonal pattern comparison foundation */
  getSeasonalPatternComparison: (projectId: string) =>
    withCache(
      `seasonal-patterns:${projectId}`,
      CACHE_TTL.HISTORY,
      () => projectIntelligenceAggregationService.getSeasonalPatternComparison(projectId)
    ),

  /** Notification event generation foundations */
  getNotificationEventFoundations: (projectId: string) =>
    withCache(
      `notification-foundations:${projectId}`,
      CACHE_TTL.CHANGES,
      () => projectIntelligenceAggregationService.getNotificationEventFoundations(projectId)
    ),

  /** Intelligent monitoring recommendation foundations */
  getMonitoringRecommendations: (projectId: string) =>
    withCache(
      `monitoring-recommendations:${projectId}`,
      CACHE_TTL.SUMMARY,
      () => projectIntelligenceAggregationService.getMonitoringRecommendations(projectId)
    ),

  /** Threshold/rule engine config */
  getThresholdRuleConfig: () =>
    withCache(
      `threshold-rule-config:v1`,
      CACHE_TTL.SUMMARY,
      () => projectIntelligenceAggregationService.getThresholdRuleEngineConfig()
    ),

  getCalibrationPresets: () =>
    withCache(
      `calibration-presets:v1`,
      CACHE_TTL.SUMMARY,
      () => projectIntelligenceAggregationService.getCalibrationPresets()
    ),

  getEffectiveCalibration: (projectId: string) =>
    withCache(
      `effective-calibration:${projectId}`,
      CACHE_TTL.SUMMARY,
      () => projectIntelligenceAggregationService.getEffectiveCalibration(projectId)
    ),

  getFieldVsSatelliteComparison: (projectId: string, indicator = "ndvi") =>
    withCache(
      `field-vs-sat:${projectId}:${indicator}`,
      CACHE_TTL.CHANGES,
      () => projectIntelligenceAggregationService.getFieldVsSatelliteComparison(projectId, indicator)
    ),

  /** Audit-ready project registry record */
  getAuditReadyRegistryRecord: (projectId: string) =>
    withCache(
      cacheKey.registry(projectId),
      CACHE_TTL.REGISTRY,
      () => projectIntelligenceAggregationService.getAuditReadyRegistryRecord(projectId)
    ),

  /** Uncached passthrough — full registry list (admin only, expensive) */
  listAuditReadyRegistry: (limit: number) =>
    projectIntelligenceAggregationService.listAuditReadyRegistry(limit),

  /** Invalidate all cached intelligence for a project */
  invalidate: (projectId: string) => {
    invalidateProjectCache(projectId);
    logger.info("Intelligence cache invalidated for project", { projectId });
  },
};
